### ISSUE TITLE
mp_init autocorrect option

### ISSUE THREAD

**Issue by tmoody** [sasjs/core#115]
The autocorrect option set in the mp_init macro is set to allow misspellings when the intent is to prevent this correction.

**Comment by allanbowe** [comment]
Goodness gracious - quite right!  We have `options autocorrect` when in fact `options noautocorrect` was the intent.  Thanks for raising!

Sticking the ref to the docs here:  https://support.sas.com/documentation/cdl/en/lesysoptsref/64892/HTML/default/viewer.htm#p0mzulmnthqs2bn1cuqm5eqlvgi8.htm
