### ISSUE TITLE
 mp_searchtool fuzzy match

### ISSUE THREAD

**Issue by kkchandok** [sasjs/core#14]
Hello,

Can the macro find fuzzy matches? . If the variable VSORRES is in multiple datasets but with a different suffix such as VSORRES1, VSORRES_02 etc...how would the macro parameters be filled. 

 %mp_searchcols(libs=work, cols=vsorres);

**Comment by allanbowe** [comment]
It's not currently set up for that but shouldn't be too hard to do, it's a matter of updating line 56 here:  https://core.sasjs.io/mp__searchcols_8sas_source.html

Would you consider making a pull request?  Else I'll jump on it when things get quieter, right now we're busy adding new features to Data Controller -[https://docs.datacontroller.io/roadmap/]( https://docs.datacontroller.io/roadmap/)

**Comment by kkchandok** [comment]
Allan,

thank you for getting back to me.
I will try to update the ode on line 56.
What is a pull request? I do not know how to do it. Also what is the purpose of the Data Controller?


Thank You,
Kamal

________________________________

**Comment by allanbowe** [comment]
Data Controller has the exact functionality you are looking for - you can literally just type your prefix into the search bar and it will instantly give you the matches. I made this video to demonstrate:


https://user-images.githubusercontent.com/4420615/118160500-0f660300-b427-11eb-842b-0ec736f9c3a0.mov

It's powered by this [macro](https://core.sasjs.io/mp__searchdata_8sas.html).  If it's interesting, just fill out the contact form [here](https:datacontroller.io/contact)

Anyway - taking a look at your issue now.

**Comment by kkchandok** [comment]
thank you Allan,

I will test it out whenI get a chnace.

Thank You,
Kamal

________________________________

**Comment by allanbowe** [comment]
Hi Kamal - I added the feature, you can see the changes here:  https://github.com/sasjs/core/pull/27/files

An example invocation can be found in the test file, here:  https://github.com/sasjs/core/blob/main/tests/base/mp_searchcols.test.sas#L44

**Comment by kkchandok** [comment]
Hi Allan,
I haven't had a chance to check the code out. I have some tight deadlines to work on. I will email you if I run into issue when I check the macro.



Thank You,
Kamal

________________________________
