### ISSUE TITLE
%mp_dirlist tries to overwrite last table

### ISSUE THREAD

**Issue by emiltb** [sasjs/core#377]
I've been working with `%mp_dirlist` and encountered some weird behaviour, in which the macro call fails dependent on whether it is run together with other parts of my script or as stand alone.

I call the macro as: `%mp_copyfolder(&DQ_INPUT_PATH.,&DQ_FULL_DEST_PATH);`

And get the error: `ERROR: You cannot create or delete datasets, views or indexes in this mode. Try the option METAOUT=DATA. Use Proc Metalib to create metadata for datasets.`

From the log it appears that it tries to overwrite a table in a libname that I have previously used, which it is not allowed to do for this libname. I believe it happens on this line in the macro (i.e. it ends up using the last table referenced in the script, which in this case is completely unrelated), but I am not sure what the best way to resolve it is: 
https://github.com/sasjs/core/blob/21d6671a5feb240eff8fee39018dd86139b5367a/base/mp_dirlist.sas#L78

**Comment by emiltb** [comment]
Nevermind - my code was missing a `;` somewhere else, and that was causing unexpected behaviour. The macro seems to be working as intended.

**Comment by allanbowe** [comment]
Glad you resolved it!

We do have tests for this macro, you can find them here:  https://core.sasjs.io/mp__dirlist_8test_8sas_source.html
