### ISSUE TITLE
Provide Base SAS support

### ISSUE THREAD

**Issue by YuryShkoda** [sasjs/core#62]
Provide support for such functions like `STPSRV_HEADER `.
From log:
```sas
ERROR 68-185: The function STPSRV_HEADER is unknown, or cannot be accessed.
```

**Comment by allanbowe** [comment]
Addressed in:  https://github.com/sasjs/core/pull/63

Needs to be added to the CLI next, here: https://github.com/sasjs/cli/issues/928
